DROP TABLE IF EXISTS notificacion CASCADE;
DROP TABLE IF EXISTS tipo_notificacion CASCADE;

DROP TABLE IF EXISTS historial CASCADE;
DROP TABLE IF EXISTS tipo_historial CASCADE;

DROP TABLE IF EXISTS seguimiento_cobro CASCADE;
DROP TABLE IF EXISTS tipo_seguimiento CASCADE;

DROP TABLE IF EXISTS pago CASCADE;

DROP TABLE IF EXISTS documento CASCADE;

DROP TABLE IF EXISTS incapacidad CASCADE;

DROP TABLE IF EXISTS entidad CASCADE;
DROP TABLE IF EXISTS tipo_incapacidad CASCADE;
DROP TABLE IF EXISTS estado_incapacidad CASCADE;

DROP TABLE IF EXISTS gestion_humana CASCADE;
DROP TABLE IF EXISTS gerencia CASCADE;
DROP TABLE IF EXISTS empleado CASCADE;

DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS rol CASCADE;

