-- Rollback schema

DROP TABLE IF EXISTS notificacion CASCADE;
DROP TABLE IF EXISTS historial CASCADE;
DROP TABLE IF EXISTS seguimiento_cobro CASCADE;
DROP TABLE IF EXISTS pago CASCADE;
DROP TABLE IF EXISTS documento CASCADE;
DROP TABLE IF EXISTS incapacidad CASCADE;
DROP TABLE IF EXISTS entidad CASCADE;
DROP TABLE IF EXISTS tipo_incapacidad CASCADE;
DROP TABLE IF EXISTS estado_incapacidad CASCADE;
DROP TABLE IF EXISTS gestion_humana CASCADE;
DROP TABLE IF EXISTS gerencia CASCADE;
DROP TABLE IF EXISTS empleado CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS permisos CASCADE;
DROP TABLE IF EXISTS rol CASCADE;
DROP TABLE IF EXISTS canal_atencion_entidad CASCADE;
DROP TABLE IF EXISTS canal_recepcion CASCADE;
DROP TABLE IF EXISTS estado_pago CASCADE;
DROP TABLE IF EXISTS tipo_pago CASCADE;
DROP TABLE IF EXISTS periodicidad_reporte CASCADE;
DROP TABLE IF EXISTS tipo_entidad CASCADE;
DROP TABLE IF EXISTS estado_documento CASCADE;
DROP TABLE IF EXISTS tipo_documento CASCADE;