// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Autentica un usuario y devuelve tokens de acceso",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Iniciar sesión",
                "parameters": [
                    {
                        "description": "Credenciales de login",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Crea un nuevo usuario en el sistema",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Registrar usuario",
                "parameters": [
                    {
                        "description": "Datos del usuario",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Obtiene nuevos tokens usando un refresh token",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Renovar token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/TokenResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/incapacidades": {
            "get": {
                "description": "Lista incapacidades con filtros y paginación. Requiere permiso 'consultar_incapacidad'",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["incapacidades"],
                "summary": "Listar incapacidades",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id_usuario", "in": "query", "type": "integer", "description": "Filtrar por usuario"},
                    {"name": "id_estado", "in": "query", "type": "integer", "description": "Filtrar por estado"},
                    {"name": "id_tipo", "in": "query", "type": "integer", "description": "Filtrar por tipo"},
                    {"name": "id_entidad", "in": "query", "type": "integer", "description": "Filtrar por entidad"},
                    {"name": "origen", "in": "query", "type": "string", "description": "Filtrar por origen"},
                    {"name": "canal_recepcion", "in": "query", "type": "string", "description": "Filtrar por canal de recepción"},
                    {"name": "page", "in": "query", "type": "integer", "default": 1, "description": "Número de página"},
                    {"name": "limit", "in": "query", "type": "integer", "default": 20, "description": "Cantidad de resultados (max: 100)"}
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedIncapacidadesResponse"
                        }
                    },
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "post": {
                "description": "Crea una nueva incapacidad. Requiere permiso 'crear_incapacidad'",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["incapacidades"],
                "summary": "Crear incapacidad",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "description": "Datos de la incapacidad",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/CrearIncapacidadRequest"}
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/IncapacidadResponse"
                        }
                    },
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/api/v1/incapacidades/{id}": {
            "get": {
                "description": "Obtiene una incapacidad por ID. Requiere permiso 'consultar_incapacidad'",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["incapacidades"],
                "summary": "Obtener incapacidad",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer", "description": "ID de la incapacidad"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/IncapacidadResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "put": {
                "description": "Actualiza una incapacidad. Requiere permiso 'editar_incapacidad'",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["incapacidades"],
                "summary": "Actualizar incapacidad",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer", "description": "ID de la incapacidad"},
                    {"description": "Datos a actualizar", "name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/ActualizarIncapacidadRequest"}}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/IncapacidadResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "delete": {
                "description": "Archiva una incapacidad (soft delete). Requiere permiso 'archivar_incapacidad'",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["incapacidades"],
                "summary": "Archivar incapacidad",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer", "description": "ID de la incapacidad"}
                ],
                "responses": {
                    "204": {"description": "No Content"},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/api/v1/incapacidades/{id}/estado": {
            "patch": {
                "description": "Cambia el estado de una incapacidad. Requiere permiso 'editar_incapacidad'",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["incapacidades"],
                "summary": "Cambiar estado de incapacidad",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer", "description": "ID de la incapacidad"},
                    {"description": "Nuevo estado", "name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/CambiarEstadoRequest"}}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/IncapacidadResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "409": {"description": "Conflict - Estado no permite transición", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/api/v1/incapacidades/estados": {
            "get": {
                "description": "Lista los estados disponibles para incapacidades. Requiere permiso 'consultar_incapacidad'",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["incapacidades"],
                "summary": "Listar estados de incapacidad",
                "security": [{"Bearer": []}],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/ListaEstadoIncapacidadResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/api/v1/incapacidades/tipos": {
            "get": {
                "description": "Lista los tipos de incapacidad disponibles. Requiere permiso 'consultar_incapacidad'",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["incapacidades"],
                "summary": "Listar tipos de incapacidad",
                "security": [{"Bearer": []}],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/ListaTipoIncapacidadResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/api/v1/incapacidades/entidades": {
            "get": {
                "description": "Lista las entidades responsables del pago (EPS, ARL, etc.). Requiere permiso 'consultar_incapacidad'",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["incapacidades"],
                "summary": "Listar entidades",
                "security": [{"Bearer": []}],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/ListaEntidadResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/api/v1/incapacidades/{id}/documentos": {
            "get": {
                "description": "Lista los documentos de una incapacidad. Requiere permiso 'consultar_incapacidad'",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["documentos"],
                "summary": "Listar documentos de incapacidad",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer", "description": "ID de la incapacidad"},
                    {"name": "estado", "in": "query", "type": "string", "description": "Filtrar por estado (Pendiente, Validado, Rechazado, Incompleto)"},
                    {"name": "tipo", "in": "query", "type": "string", "description": "Filtrar por tipo de documento"},
                    {"name": "page", "in": "query", "type": "integer", "default": 1, "description": "Número de página"},
                    {"name": "limit", "in": "query", "type": "integer", "default": 20, "description": "Cantidad de resultados"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/PaginatedDocumentosResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "post": {
                "description": "Sube un documento para una incapacidad. Requiere permiso 'crear_incapacidad' o 'editar_incapacidad'",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["documentos"],
                "summary": "Subir documento",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer", "description": "ID de la incapacidad"},
                    {"description": "Datos del documento", "name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/SubirDocumentoRequest"}}
                ],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/DocumentoResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/api/v1/documentos/{id}/validar": {
            "patch": {
                "description": "Valida o rechaza un documento. Requiere permiso 'validar_documentos' o 'editar_incapacidad'",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["documentos"],
                "summary": "Validar documento",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer", "description": "ID del documento"},
                    {"description": "Datos de validación", "name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/ValidarDocumentoRequest"}}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/DocumentoResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/api/v1/documentos/{id}": {
            "delete": {
                "description": "Elimina un documento (soft delete). Requiere permiso 'editar_incapacidad'",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["documentos"],
                "summary": "Eliminar documento",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer", "description": "ID del documento"}
                ],
                "responses": {
                    "204": {"description": "No Content"},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/api/v1/incapacidades/{id}/historial": {
            "get": {
                "description": "Lista el historial de cambios de una incapacidad. Requiere permiso 'consultar_incapacidad' o 'consultar_historial'",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["historial"],
                "summary": "Listar historial de incapacidad",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer", "description": "ID de la incapacidad"},
                    {"name": "id_tipo_historial", "in": "query", "type": "integer", "description": "Filtrar por tipo de historial"},
                    {"name": "page", "in": "query", "type": "integer", "default": 1, "description": "Número de página"},
                    {"name": "limit", "in": "query", "type": "integer", "default": 20, "description": "Cantidad de resultados"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/PaginatedHistorialResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/api/v1/usuarios": {
            "get": {
                "description": "Lista usuarios con paginación y filtros",
                "produces": ["application/json"],
                "tags": ["usuarios"],
                "summary": "Listar usuarios",
                "parameters": [
                    {"name": "estado", "in": "query", "type": "boolean"},
                    {"name": "id_rol", "in": "query", "type": "integer"},
                    {"name": "page", "in": "query", "type": "integer", "default": 1},
                    {"name": "limit", "in": "query", "type": "integer", "default": 20}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/PaginatedUsuariosResponse"}}
                }
            },
            "post": {
                "description": "Crea un nuevo usuario",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["usuarios"],
                "summary": "Crear usuario",
                "parameters": [
                    {"name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/CrearUsuarioRequest"}}
                ],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/UsuarioResponse"}}
                }
            }
        },
        "/api/v1/usuarios/{id}": {
            "get": {
                "description": "Obtiene un usuario por ID",
                "produces": ["application/json"],
                "tags": ["usuarios"],
                "summary": "Obtener usuario",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/UsuarioResponse"}}
                }
            },
            "put": {
                "description": "Actualiza un usuario",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["usuarios"],
                "summary": "Actualizar usuario",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"},
                    {"name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/ActualizarUsuarioRequest"}}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/UsuarioResponse"}}
                }
            },
            "delete": {
                "description": "Elimina un usuario (soft delete)",
                "tags": ["usuarios"],
                "summary": "Eliminar usuario",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "OK"}
                }
            }
        },
        "/api/v1/usuarios/{id}/estado": {
            "patch": {
                "description": "Cambia el estado de un usuario",
                "consumes": ["application/json"],
                "tags": ["usuarios"],
                "summary": "Cambiar estado",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"},
                    {"name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/CambiarEstadoUsuarioRequest"}}
                ],
                "responses": {
                    "200": {"description": "OK"}
                }
            }
        },
        "/api/v1/usuarios/{id}/rol": {
            "post": {
                "description": "Asigna un rol a un usuario",
                "consumes": ["application/json"],
                "tags": ["usuarios"],
                "summary": "Asignar rol",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"},
                    {"name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/AsignarRolRequest"}}
                ],
                "responses": {
                    "200": {"description": "OK"}
                }
            }
        },
        "/api/v1/usuarios/{id}/password": {
            "post": {
                "description": "Cambia la contraseña del usuario",
                "consumes": ["application/json"],
                "tags": ["usuarios"],
                "summary": "Cambiar contraseña",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"},
                    {"name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/CambiarPasswordRequest"}}
                ],
                "responses": {
                    "200": {"description": "OK"}
                }
            }
        },
        "/api/v1/roles": {
            "get": {
                "description": "Lista roles con paginación",
                "produces": ["application/json"],
                "tags": ["roles"],
                "summary": "Listar roles",
                "parameters": [
                    {"name": "page", "in": "query", "type": "integer", "default": 1},
                    {"name": "limit", "in": "query", "type": "integer", "default": 20}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/PaginatedRolesResponse"}}
                }
            },
            "post": {
                "description": "Crea un nuevo rol",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["roles"],
                "summary": "Crear rol",
                "parameters": [
                    {"name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/CrearRolRequest"}}
                ],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/RolResponse"}}
                }
            }
        },
        "/api/v1/roles/{id}": {
            "get": {
                "description": "Obtiene un rol por ID",
                "produces": ["application/json"],
                "tags": ["roles"],
                "summary": "Obtener rol",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/RolResponse"}}
                }
            },
            "put": {
                "description": "Actualiza un rol",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["roles"],
                "summary": "Actualizar rol",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"},
                    {"name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/ActualizarRolRequest"}}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/RolResponse"}}
                }
            },
            "delete": {
                "description": "Elimina un rol",
                "tags": ["roles"],
                "summary": "Eliminar rol",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "OK"}
                }
            }
        }
    },
    "definitions": {
        "UsuarioResponse": {
            "type": "object",
            "properties": {
                "id_usuario": {"type": "integer"},
                "id_rol": {"type": "integer"},
                "nombre_rol": {"type": "string"},
                "nombre": {"type": "string"},
                "correo": {"type": "string"},
                "numero_celular": {"type": "string"},
                "direccion": {"type": "string"},
                "numero_documento": {"type": "string"},
                "numero_acudiente": {"type": "string"},
                "estado": {"type": "boolean"},
                "created_at": {"type": "string", "format": "date-time"},
                "updated_at": {"type": "string", "format": "date-time"}
            }
        },
        "CrearUsuarioRequest": {
            "type": "object",
            "required": ["id_rol", "nombre", "correo", "password", "numero_documento"],
            "properties": {
                "id_rol": {"type": "integer", "example": 1},
                "nombre": {"type": "string", "example": "Juan Pérez"},
                "correo": {"type": "string", "example": "juan@ejemplo.com"},
                "numero_celular": {"type": "string", "example": "+573001234567"},
                "direccion": {"type": "string", "example": "Calle 123 #45-67"},
                "password": {"type": "string", "example": "contraseña123"},
                "numero_documento": {"type": "string", "example": "12345678"},
                "numero_acudiente": {"type": "string"}
            }
        },
        "ActualizarUsuarioRequest": {
            "type": "object",
            "required": ["id_rol", "nombre", "correo"],
            "properties": {
                "id_rol": {"type": "integer"},
                "nombre": {"type": "string"},
                "correo": {"type": "string"},
                "numero_celular": {"type": "string"},
                "direccion": {"type": "string"}
            }
        },
        "CambiarPasswordRequest": {
            "type": "object",
            "required": ["password_actual", "password_nuevo"],
            "properties": {
                "password_actual": {"type": "string"},
                "password_nuevo": {"type": "string"}
            }
        },
        "CambiarEstadoUsuarioRequest": {
            "type": "object",
            "required": ["estado"],
            "properties": {
                "estado": {"type": "boolean"}
            }
        },
        "AsignarRolRequest": {
            "type": "object",
            "required": ["id_rol"],
            "properties": {
                "id_rol": {"type": "integer"}
            }
        },
        "PaginatedUsuariosResponse": {
            "type": "object",
            "properties": {
                "success": {"type": "boolean"},
                "message": {"type": "string"},
                "data": {
                    "type": "object",
                    "properties": {
                        "items": {"type": "array", "items": {"$ref": "#/definitions/UsuarioResponse"}},
                        "total": {"type": "integer"},
                        "page": {"type": "integer"},
                        "limit": {"type": "integer"},
                        "total_pages": {"type": "integer"}
                    }
                }
            }
        },
        "RolResponse": {
            "type": "object",
            "properties": {
                "id_rol": {"type": "integer"},
                "nombre": {"type": "string"},
                "permisos": {"type": "array", "items": {"type": "string"}}
            }
        },
        "CrearRolRequest": {
            "type": "object",
            "required": ["nombre", "permisos"],
            "properties": {
                "nombre": {"type": "string", "example": "Gestor"},
                "permisos": {"type": "array", "items": {"type": "string"}, "example": ["incapacidades.crear", "incapacidades.ver"]}
            }
        },
        "ActualizarRolRequest": {
            "type": "object",
            "required": ["nombre", "permisos"],
            "properties": {
                "nombre": {"type": "string"},
                "permisos": {"type": "array", "items": {"type": "string"}}
            }
        },
        "PaginatedRolesResponse": {
            "type": "object",
            "properties": {
                "success": {"type": "boolean"},
                "message": {"type": "string"},
                "data": {
                    "type": "object",
                    "properties": {
                        "items": {"type": "array", "items": {"$ref": "#/definitions/RolResponse"}},
                        "total": {"type": "integer"},
                        "page": {"type": "integer"},
                        "limit": {"type": "integer"},
                        "total_pages": {"type": "integer"}
                    }
                }
            }
        },
        "LoginRequest": {
            "type": "object",
            "required": ["email", "password"],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "usuario@ejemplo.com"
                },
                "password": {
                    "type": "string",
                    "example": "contraseña123"
                }
            }
        },
        "RegisterRequest": {
            "type": "object",
            "required": ["nombre", "email", "password", "numero_documento"],
            "properties": {
                "nombre": {
                    "type": "string",
                    "example": "Juan Pérez"
                },
                "email": {
                    "type": "string",
                    "example": "juan@ejemplo.com"
                },
                "password": {
                    "type": "string",
                    "example": "contraseña123"
                },
                "numero_documento": {
                    "type": "string",
                    "example": "12345678"
                },
                "numero_celular": {
                    "type": "string",
                    "example": "+573001234567"
                },
                "direccion": {
                    "type": "string",
                    "example": "Calle 123 #45-67"
                }
            }
        },
        "RefreshTokenRequest": {
            "type": "object",
            "required": ["refresh_token"],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "UserResponse": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "nombre": {"type": "string"},
                "correo": {"type": "string"},
                "numero_celular": {"type": "string"},
                "direccion": {"type": "string"},
                "numero_documento": {"type": "string"},
                "estado": {"type": "boolean"},
                "rol": {"$ref": "#/definitions/RoleResponse"},
                "created_at": {"type": "string", "format": "date-time"}
            }
        },
        "RoleResponse": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "nombre": {"type": "string"},
                "permisos": {"type": "array", "items": {"type": "string"}}
            }
        },
        "LoginResponse": {
            "type": "object",
            "properties": {
                "user": {"$ref": "#/definitions/UserResponse"},
                "access_token": {"type": "string"},
                "refresh_token": {"type": "string"},
                "token_type": {"type": "string", "example": "Bearer"},
                "expires_in": {"type": "integer"}
            }
        },
        "TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {"type": "string"},
                "refresh_token": {"type": "string"},
                "token_type": {"type": "string", "example": "Bearer"},
                "expires_in": {"type": "integer"}
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "success": {"type": "boolean", "example": false},
                "message": {"type": "string"},
                "error": {
                    "type": "object",
                    "properties": {
                        "code": {"type": "string"},
                        "details": {}
                    }
                }
            }
        },
        "IncapacidadResponse": {
            "type": "object",
            "properties": {
                "id_incapacidad": {"type": "integer"},
                "id_usuario": {"type": "integer"},
                "canal_recepcion": {"type": "string"},
                "titulo": {"type": "string"},
                "fecha_inicio": {"type": "string", "example": "2024-01-15"},
                "fecha_fin": {"type": "string", "example": "2024-01-30"},
                "origen": {"type": "string"},
                "fecha_radicacion": {"type": "string", "example": "2024-01-20"},
                "fecha_pago": {"type": "string", "example": "2024-02-15"},
                "observaciones": {"type": "string"},
                "estado": {"$ref": "#/definitions/EstadoIncapacidadResponse"},
                "tipo": {"$ref": "#/definitions/TipoIncapacidadResponse"},
                "entidad": {"$ref": "#/definitions/EntidadResponse"},
                "created_by": {"type": "integer"},
                "created_at": {"type": "string", "format": "date-time"},
                "updated_at": {"type": "string", "format": "date-time"}
            }
        },
        "EstadoIncapacidadResponse": {
            "type": "object",
            "properties": {
                "id_estado": {"type": "integer"},
                "nombre": {"type": "string"},
                "descripcion": {"type": "string"},
                "permite_transicion": {"type": "boolean"}
            }
        },
        "TipoIncapacidadResponse": {
            "type": "object",
            "properties": {
                "id_tipo": {"type": "integer"},
                "nombre": {"type": "string"},
                "documentos_requeridos": {"type": "array", "items": {"type": "string"}}
            }
        },
        "EntidadResponse": {
            "type": "object",
            "properties": {
                "id_entidad": {"type": "integer"},
                "nombre": {"type": "string"},
                "tipo": {"type": "string", "example": "EPS"},
                "plazo_transcripcion_dias": {"type": "integer"},
                "tiempo_maximo_pago_dias": {"type": "integer"},
                "canal_atencion": {"type": "string"},
                "canales_atencion": {"type": "array", "items": {"type": "string"}},
                "requiere_transcripcion": {"type": "boolean"}
            }
        },
        "CrearIncapacidadRequest": {
            "type": "object",
            "required": ["id_tipo", "id_entidad", "titulo", "fecha_inicio", "origen"],
            "properties": {
                "id_usuario": {"type": "integer", "description": "ID del usuario titular de la incapacidad (propietario)"},
                "id_estado": {"type": "integer", "description": "ID del estado inicial (opcional)"},
                "id_tipo": {"type": "integer", "example": 1, "description": "Tipo de incapacidad"},
                "id_entidad": {"type": "integer", "example": 1, "description": "Entidad responsable del pago"},
                "canal_recepcion": {"type": "string", "example": "Recepción física", "description": "Canal de recepción"},
                "titulo": {"type": "string", "example": "Incapacidad por enfermedad general", "description": "Título o descripción breve"},
                "fecha_inicio": {"type": "string", "example": "2024-01-15", "description": "Fecha de inicio (YYYY-MM-DD)"},
                "fecha_fin": {"type": "string", "example": "2024-01-30", "description": "Fecha de fin (YYYY-MM-DD)"},
                "origen": {"type": "string", "example": "laboral", "description": "Origen (laboral, comun, etc.)"},
                "fecha_radicacion": {"type": "string", "example": "2024-01-20", "description": "Fecha de radicación ante la entidad"},
                "fecha_pago": {"type": "string", "example": "2024-02-15", "description": "Fecha de pago"},
                "observaciones": {"type": "string", "description": "Notas adicionales"}
            }
        },
        "ActualizarIncapacidadRequest": {
            "type": "object",
            "properties": {
                "id_tipo": {"type": "integer"},
                "id_entidad": {"type": "integer"},
                "canal_recepcion": {"type": "string"},
                "titulo": {"type": "string"},
                "fecha_inicio": {"type": "string"},
                "fecha_fin": {"type": "string"},
                "origen": {"type": "string"},
                "fecha_radicacion": {"type": "string"},
                "fecha_pago": {"type": "string"},
                "observaciones": {"type": "string"}
            }
        },
        "CambiarEstadoRequest": {
            "type": "object",
            "required": ["id_estado"],
            "properties": {
                "id_estado": {"type": "integer", "example": 2, "description": "ID del nuevo estado"},
                "observaciones": {"type": "string", "description": "Observaciones del cambio de estado"}
            }
        },
        "PaginatedIncapacidadesResponse": {
            "type": "object",
            "properties": {
                "success": {"type": "boolean"},
                "message": {"type": "string"},
                "data": {
                    "type": "object",
                    "properties": {
                        "items": {"type": "array", "items": {"$ref": "#/definitions/IncapacidadResponse"}},
                        "total": {"type": "integer"},
                        "page": {"type": "integer"},
                        "limit": {"type": "integer"},
                        "total_pages": {"type": "integer"}
                    }
                }
            }
        },
        "ListaEstadoIncapacidadResponse": {
            "type": "object",
            "properties": {
                "success": {"type": "boolean"},
                "message": {"type": "string"},
                "data": {"type": "array", "items": {"$ref": "#/definitions/EstadoIncapacidadResponse"}}
            }
        },
        "ListaTipoIncapacidadResponse": {
            "type": "object",
            "properties": {
                "success": {"type": "boolean"},
                "message": {"type": "string"},
                "data": {"type": "array", "items": {"$ref": "#/definitions/TipoIncapacidadResponse"}}
            }
        },
        "ListaEntidadResponse": {
            "type": "object",
            "properties": {
                "success": {"type": "boolean"},
                "message": {"type": "string"},
                "data": {"type": "array", "items": {"$ref": "#/definitions/EntidadResponse"}}
            }
        },
        "SubirDocumentoRequest": {
            "type": "object",
            "required": ["id_incapacidad", "nombre", "tipo", "url", "formato"],
            "properties": {
                "id_incapacidad": {"type": "integer", "example": 1, "description": "ID de la incapacidad"},
                "nombre": {"type": "string", "example": "Certificado médico.pdf", "description": "Nombre del documento"},
                "tipo": {"type": "string", "example": "Certificado de incapacidad", "description": "Tipo de documento"},
                "url": {"type": "string", "example": "https://storage.com/docs/123.pdf", "description": "URL del documento"},
                "formato": {"type": "string", "example": "pdf", "description": "Formato del archivo (pdf, jpg, png)"}
            }
        },
        "ValidarDocumentoRequest": {
            "type": "object",
            "required": ["estado"],
            "properties": {
                "estado": {"type": "string", "example": "Validado", "description": "Estado: Validado, Rechazado o Incompleto"},
                "comentario": {"type": "string", "description": "Comentario de validación"}
            }
        },
        "DocumentoResponse": {
            "type": "object",
            "properties": {
                "id_documento": {"type": "integer"},
                "id_incapacidad": {"type": "integer"},
                "nombre": {"type": "string"},
                "tipo": {"type": "string"},
                "url": {"type": "string"},
                "formato": {"type": "string"},
                "estado": {"type": "string"},
                "comentario": {"type": "string"},
                "fecha_carga": {"type": "string"},
                "validado_por": {"type": "integer"},
                "fecha_validacion": {"type": "string"},
                "created_at": {"type": "string", "format": "date-time"}
            }
        },
        "PaginatedDocumentosResponse": {
            "type": "object",
            "properties": {
                "success": {"type": "boolean"},
                "message": {"type": "string"},
                "data": {
                    "type": "object",
                    "properties": {
                        "items": {"type": "array", "items": {"$ref": "#/definitions/DocumentoResponse"}},
                        "total": {"type": "integer"},
                        "page": {"type": "integer"},
                        "limit": {"type": "integer"},
                        "total_pages": {"type": "integer"}
                    }
                }
            }
        },
        "HistorialResponse": {
            "type": "object",
            "properties": {
                "id_historial": {"type": "integer"},
                "id_incapacidad": {"type": "integer"},
                "id_tipo_historial": {"type": "integer"},
                "nombre_tipo": {"type": "string"},
                "descripcion": {"type": "string"},
                "fecha": {"type": "string"},
                "gestor_id": {"type": "integer"}
            }
        },
        "PaginatedHistorialResponse": {
            "type": "object",
            "properties": {
                "success": {"type": "boolean"},
                "message": {"type": "string"},
                "data": {
                    "type": "object",
                    "properties": {
                        "items": {"type": "array", "items": {"$ref": "#/definitions/HistorialResponse"}},
                        "total": {"type": "integer"},
                        "page": {"type": "integer"},
                        "limit": {"type": "integer"},
                        "total_pages": {"type": "integer"}
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Disability System API",
	Description:      "API para gestión de incapacidades y-system",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
